# Generated by Django 2.0 on 2018-08-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_total',
        ),
    ]
